apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: default
automountServiceAccountToken: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - name: backend
        image: thush1990/demo-ci:backend3
        ports:
        - containerPort: 5200          

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    service: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: "bind-backend"
    protocol: "TCP"
    port: 5200
    targetPort: 5200    