apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thush1990/demo-ci:backend
        imagePullPolicy: Never
        ports:
        - containerPort: 5200          

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend
spec:
  selector:
    app: backend
  ports:
  - name: "bind-backend"
    protocol: "TCP"
    port: 5200
    targetPort: 5200    