apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-frontend
        image: thush1990/demo-ci:14
        imagePullPolicy: Never
        ports:
        - containerPort: 5100
      - name: flask-backend
        image: flask-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5200          