apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: default
automountServiceAccountToken: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'backend:5200'
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: thush1990/demo-ci:17
        ports:
        - containerPort: 5100    

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    service: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: "bind-frontend"
    protocol: "TCP"
    port: 5100
    targetPort: 5100
