apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thush1990/demo-ci:14
        ports:
        - containerPort: 5100    

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: "bind-frontend"
    protocol: "TCP"
    port: 5100
    targetPort: 5100
